In [12]:
import torch
import numpy as np

In [19]:
data = [[1, 2], [3, 4]]
nparr = np.array(data)


In [14]:
def from_data():
    x_data = torch.tensor(data)
    print(x_data)

from_data()


tensor([[1, 2],
        [3, 4]])


In [15]:
def from_nparr():
    x_np = torch.from_numpy(nparr)
    print(x_np)

from_nparr()


tensor([[1, 2],
        [3, 4]], dtype=torch.int32)


In [21]:
def from_tensor():
    x_data = torch.tensor(data)
    x_ones = torch.ones_like(x_data)
    x_rand = torch.rand_like(x_data, dtype=torch.float)
    print(f'{x_ones}\n{x_rand}')

from_tensor()


tensor([[1, 1],
        [1, 1]])
tensor([[0.3301, 0.5680],
        [0.8497, 0.1193]])


In [22]:
def rand_constant_tensor():
    shape = (2, 3,) 
    rand_tensor = torch.rand(shape)
    ones_tensor = torch.ones(shape)
    zeros_tensor = torch.zeros(shape)
    print(f'{rand_tensor}\n{ones_tensor}\n{zeros_tensor}')

rand_constant_tensor()

tensor([[0.5953, 0.0363, 0.5940],
        [0.1164, 0.0565, 0.8637]])
tensor([[1., 1., 1.],
        [1., 1., 1.]])
tensor([[0., 0., 0.],
        [0., 0., 0.]])


In [24]:
def attribute():
    tensor = torch.rand(3, 5)
    print(f'{tensor.shape}\n{tensor.dtype}\n{tensor.device}')

attribute()

torch.Size([3, 5])
torch.float32
cpu


In [26]:
def gpu_tensor():
    tensor = torch.rand(3, 4)
    if torch.cuda.is_available():
        tensor = tensor.to('cuda')
        print(tensor)

gpu_tensor()

tensor([[0.0378, 0.9506, 0.3607, 0.6030],
        [0.4642, 0.9456, 0.7718, 0.5216],
        [0.1175, 0.2394, 0.6126, 0.5832]], device='cuda:0')


In [31]:
def index_slice():
    tensor = torch.tensor([[i * 4 + j for j in range(4)] for i in range(4)])
    print(tensor)
    print('First row: ',tensor[0])
    print('First column: ', tensor[:, 0])
    print('Last column:', tensor[..., -1])
    tensor[:, 1] = 0
    print(tensor)

index_slice()

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11],
        [12, 13, 14, 15]])
First row:  tensor([0, 1, 2, 3])
First column:  tensor([ 0,  4,  8, 12])
Last column: tensor([ 3,  7, 11, 15])
tensor([[ 0,  0,  2,  3],
        [ 4,  0,  6,  7],
        [ 8,  0, 10, 11],
        [12,  0, 14, 15]])


In [41]:
def torch_cat():
    t1d = torch.tensor([i for i in range(3)])
    print(t1d)
    # 차원이 하나라서 dim=0으로 붙일 수 밖에 없다
    t = torch.cat([t1d, t1d], dim=0)
    print(t)

    t2d = torch.tensor([[i * 3 + j for j in range(3)] for i in range(2)])
    print(t2d)
    # 차원이 두 개라서 0, 1 두 방향으로 붙일 수 있다.
    t = list(map(lambda x : torch.cat([t2d, t2d], dim=x), range(2)))
    print(*t, sep='\n')

torch_cat()

tensor([0, 1, 2])
tensor([0, 1, 2, 0, 1, 2])
tensor([[0, 1, 2],
        [3, 4, 5]])
tensor([[0, 1, 2],
        [3, 4, 5],
        [0, 1, 2],
        [3, 4, 5]])
tensor([[0, 1, 2, 0, 1, 2],
        [3, 4, 5, 3, 4, 5]])


In [58]:
def torch_stack():
    t2d = torch.tensor([[i * 4 + j for j in range(4)] for i in range(3)])
    print(t2d, t2d.shape)

    # 0차원 방향으로 쌓는다 = 새로 생기는 차원을 0차원으로 한다
    td = list(map(lambda x : torch.stack([t2d, t2d], dim=x), range(3)))
    for t in td:
        print(t, t.shape)

torch_stack()

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]]) torch.Size([3, 4])
tensor([[[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11]],

        [[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11]]]) torch.Size([2, 3, 4])
tensor([[[ 0,  1,  2,  3],
         [ 0,  1,  2,  3]],

        [[ 4,  5,  6,  7],
         [ 4,  5,  6,  7]],

        [[ 8,  9, 10, 11],
         [ 8,  9, 10, 11]]]) torch.Size([3, 2, 4])
tensor([[[ 0,  0],
         [ 1,  1],
         [ 2,  2],
         [ 3,  3]],

        [[ 4,  4],
         [ 5,  5],
         [ 6,  6],
         [ 7,  7]],

        [[ 8,  8],
         [ 9,  9],
         [10, 10],
         [11, 11]]]) torch.Size([3, 4, 2])


In [70]:
def torch_arith():
    tensor = torch.tensor([[i * 3 + j for j in range(3)] for i in range(3)])
    print(tensor)
    
    # 행렬곱
    y1 = tensor @ tensor
    y2 = tensor.matmul(tensor)
    y3 = torch.matmul(tensor, tensor)
    print(y3)

    # 요소별 곱
    z1 = tensor * tensor
    z2 = tensor.mul(tensor)
    z3 = torch.mul(tensor, tensor)
    print(z3)

torch_arith()

tensor([[0, 1, 2],
        [3, 4, 5],
        [6, 7, 8]])
tensor([[ 15,  18,  21],
        [ 42,  54,  66],
        [ 69,  90, 111]])
tensor([[ 0,  1,  4],
        [ 9, 16, 25],
        [36, 49, 64]])


In [73]:
def single_elem_tensor():
    tensor = torch.tensor([[i * 3 + j for j in range(3)] for i in range(3)])
    print(tensor)
    agg = tensor.sum()
    print(agg, type(agg))
    agg_item = agg.item()
    print(agg_item, type(agg_item))

single_elem_tensor()

tensor([[0, 1, 2],
        [3, 4, 5],
        [6, 7, 8]])
tensor(36) <class 'torch.Tensor'>
36 <class 'int'>


In [77]:
def torch_to_numpy():
    t = torch.ones(5)
    n = t.numpy()
    print(t)
    print(n)

    t.add_(1)
    print(t)
    print(n)

torch_to_numpy()

tensor([1., 1., 1., 1., 1.])
[1. 1. 1. 1. 1.]
tensor([2., 2., 2., 2., 2.])
[2. 2. 2. 2. 2.]


In [80]:
def numpy_to_torch():
    n = np.ones(5)
    t = torch.from_numpy(n)
    print(t)
    print(n)

    np.add(n, 1, out=n)
    print(t)
    print(n)

numpy_to_torch()

tensor([1., 1., 1., 1., 1.], dtype=torch.float64)
[1. 1. 1. 1. 1.]
tensor([2., 2., 2., 2., 2.], dtype=torch.float64)
[2. 2. 2. 2. 2.]
